WITH CTE AS 
(
    SELECT CONCAT(LAT, ',', LON) AS LOCATION 
    FROM INSURANCE 
    GROUP BY LAT, LON 
    HAVING COUNT(PID) > 1
),
CTE2 AS 
(
    SELECT DISTINCT I1.* 
    FROM INSURANCE I1 
    LEFT JOIN INSURANCE I2 ON I1.TIV_2015 = I2.TIV_2015 
    WHERE I1.PID <> I2.PID 
    AND CONCAT(I1.LAT, ',', I1.LON) NOT IN (SELECT LOCATION FROM CTE)   
)
SELECT ROUND(SUM(TIV_2016), 2) AS TIV_2016 
FROM CTE2;
