# Write your MySQL query statement below
SELECT REQUEST_AT AS DAY,  ROUND((SUM(IF(STATUS!='COMPLETED',1,0))/COUNT(STATUS)),2) AS "CANCELLATION RATE"
FROM TRIPS
WHERE REQUEST_AT >= "2013-10-01" AND  REQUEST_AT <="2013-10-03"
AND CLIENT_ID NOT IN (SELECT USERS_ID FROM USERS WHERE BANNED='YES')
AND DRIVER_ID NOT IN (SELECT USERS_ID FROM USERS WHERE BANNED='YES')
GROUP BY REQUEST_AT

