# Write your MySQL query statement below
WITH CTE AS 
(
SELECT DEPARTMENTID AS ID,NAME,SALARY,DENSE_RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS R FROM EMPLOYEE
)

SELECT D.NAME AS DEPARTMENT,CTE.NAME AS EMPLOYEE,CTE.SALARY AS SALARY FROM CTE INNER JOIN DEPARTMENT D ON CTE.ID=D.ID WHERE R<=3 