WITH CTE AS
( 
    SELECT MR.*, U.NAME, MO.TITLE
    FROM MOVIES MO
    INNER JOIN MOVIERATING MR ON MO.MOVIE_ID = MR.MOVIE_ID
    INNER JOIN USERS U ON MR.USER_ID = U.USER_ID 
)

(SELECT NAME AS RESULTS
FROM CTE
GROUP BY NAME
ORDER BY COUNT(*) DESC, NAME
LIMIT 1)

UNION ALL

(SELECT TITLE AS RESULTS
FROM CTE
WHERE DATE_FORMAT(CREATED_AT, '%Y-%m') = '2020-02'
GROUP BY TITLE
ORDER BY AVG(RATING) DESC, TITLE
LIMIT 1);
