WITH CTE AS 
(
    SELECT REQUESTER_ID AS ID, ACCEPTER_ID FROM REQUESTACCEPTED 
    UNION 
    SELECT ACCEPTER_ID AS ID, REQUESTER_ID FROM REQUESTACCEPTED 
)
SELECT ID, COUNT(DISTINCT ACCEPTER_ID) AS NUM 
FROM CTE 
GROUP BY ID 
ORDER BY NUM DESC 
LIMIT 1;
